export const ENV = {
  PORT: Number(process.env["PORT"] ?? 5001),
  NODE_ENV: process.env["NODE_ENV"] ?? "development",
  DATABASE_URL: process.env["DATABASE_URL"] ?? "",
  CLIENT_URL: process.env["CLIENT_URL"] ?? "http://localhost:3000",
  APP_URL: process.env["APP_URL"] ?? "http://localhost:5001",
  JWT_ACCESS_SECRET: process.env["JWT_ACCESS_SECRET"] ?? "",
  JWT_REFRESH_SECRET: process.env["JWT_REFRESH_SECRET"] ?? "",
  JWT_ACCESS_EXPIRES_IN: process.env["JWT_ACCESS_EXPIRES_IN"] ?? "15m",
  JWT_REFRESH_EXPIRES_IN: process.env["JWT_REFRESH_EXPIRES_IN"] ?? "7d",
  GMAIL_OAUTH_CLIENT_ID: process.env["GMAIL_OAUTH_CLIENT_ID"] ?? "",
  GMAIL_OAUTH_CLIENT_SECRET: process.env["GMAIL_OAUTH_CLIENT_SECRET"] ?? "",
  GMAIL_OAUTH_REFRESH_TOKEN: process.env["GMAIL_OAUTH_REFRESH_TOKEN"] ?? "",
  GMAIL_SENDER_ADDRESS: process.env["GMAIL_SENDER_ADDRESS"] ?? "",
  ULTRAMSG_INSTANCE_ID: process.env["ULTRAMSG_INSTANCE_ID"] ?? "",
  ULTRAMSG_TOKEN: process.env["ULTRAMSG_TOKEN"] ?? "",
  PAYSTACK_SECRET_KEY: process.env["PAYSTACK_SECRET_KEY"] ?? "",
  ADDITIONAL_ORIGINS: process.env["ADDITIONAL_ORIGINS"] ?? "",
} as const;
